version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  centrifugo:
    image: centrifugo/centrifugo:v5
    ports:
      - "8000:8000"
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    networks:
      - chat-network

  auth-service:
    build: ./auth-service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=chat_app
    depends_on:
      - postgres
    networks:
      - chat-network

  chat-service:
    build: ./chat-service
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=chat_app
      - CENTRIFUGO_URL=http://centrifugo:8000
      - CENTRIFUGO_API_KEY=your-api-key
      - PORT=50052
    depends_on:
      - postgres
      - centrifugo
    networks:
      - chat-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=auth-service:50051
    depends_on:
      - auth-service
    networks:
      - chat-network

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge