version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  centrifugo:
    image: centrifugo/centrifugo:v5
    ports:
      - "8000:8000"
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    networks:
      - chat-network

  auth-service:
    build: ./auth-service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=chat_app
    depends_on:
      - postgres
    networks:
      - chat-network

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge